server:
  port: 8081
  #servlet:
    #context-path: /backendServer

springfox:
  documentation:
    swagger-ui:
      base-url: /developer

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: xiroi
    password: 123456
    url: jdbc:mysql://localhost:3306/test_database
  redis:
    timeout: 10000ms
    host: 127.0.0.1
    port: 6379
    password: root
    database: 0
    lettuce:
      pool:
        max-active: 1024
        max-wait: 10000ms
        #最大空闲连接
        max-idle: 200
        min-idle: 5
#邮件配置
#https://blog.csdn.net/a030455/article/details/109788594
#https://service.mail.qq.com/cgi-bin/help?subtype=1&&no=369&&id=28
  mail:
    host: smtp.qq.com
    username: XXXXXXX@qq.com
    password: #SMTP密码
    #发送邮件服务器：smtp.qq.com，使用SSL，端口号465或587
    port: 465
    default-encoding: UTF-8
    protocol: smtp
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          ssl:
            enable: true
          socketFactory:
            port: 465
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
  #http://localhost:15672/
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
    #消息确认回调
    publisher-confirm-type: correlated
    #消息失败回调
    publisher-returns: true
  thymeleaf:
    prefix: classpath:/templates/
  messages:
    encoding: UTF-8
    basename: i18n/systemMessage

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      table-prefix: tab_
      update-strategy: not_empty
  mapper-locations: classpath:/mappers/*.xml

#logging:
  #config: classpath:log4j.xml

jwt:
  #JWT存储的请求头
  tokenHeader: Authorization
  #JWT加解密码使用的密钥
  secret: login-secret
  #JWT的超时时间
  expiration: 604800
  #JWT负载中拿到开头
  tokenHead: Bearer

developer:
  username: developer
  password: 123456
  role: ROLE_developer
  email: #TestMail
